### ISSUE TITLE
Add support for length-delimited strings

### ISSUE THREAD

**Issue by ik80** [lemire/fast_double_parser#12]
Would be nice.

**Comment by ik-funcom** [comment]
OK, I have to elaborate a little bit. The functions in the library parse null terminated strings. However, most high performance parsing applications would need to parse the data in place, with no null terminator. 

Basically I suggest it would be useful to have versions of functions taking (const char* begin, const char* end, .. ) in addition to just (const char* str, ... )

**Comment by lemire** [comment]
I have reworded the issue. It is easy to get a char * pointer from a string_view so supporting string_view (a C++17 feature) is not really what is important.

**Comment by ik80** [comment]
I might make a pr

**Comment by lemire** [comment]
Solved.
