### ISSUE TITLE
Comma as decimal separator doesn't work

### ISSUE THREAD

**Issue by jm4R** [lemire/fast_double_parser#2]
There is no version which support for example "3,14159" string.

**Comment by lemire** [comment]
That's correct, there is no localization support whatsoever currently. This is deliberate: the JSON standard we refer to for number formatting is not localized.

Of course, we could handle localized floats, maybe via templating.

Contributions are invited.

**Comment by vaz-rodrigo** [comment]
Why not simply supply a parametrized version where decimal separator can be used?

**Comment by lemire** [comment]
Localization is more than just replacing the period by another character. But if all we want is to replace the decimal separator, then sure, it can be a runtime parameter.

**Comment by vaz-rodrigo** [comment]
Well, yes, but when you are parsing numbers you only need the decimal separator of the culture (thousands separator too but I don't think you are considering it in the code?). You could have a method that receives a locale object and use a numpunct facet to get the decimal (or receives the facet itself) but I imagine doing that will eat through all the optimization

**Comment by lemire** [comment]
Code contributions are invited! This is not something I will work on, but if someone wants to take a shot at it...

**Comment by jm4R** [comment]
@lemire I've just created a commit with the support for custom decimal separator(s). It requires the C++17 support. Will you accept such pull request or should I apply workaround for C++11?

The commit:
https://github.com/jm4R/fast_double_parser/commit/7dab06b857324ccdd02777d2cb355934c41dca83

**Comment by lemire** [comment]
Can't we just #ifdef for C++11 support?
```
#if ( __cplusplus < 201703L)
...
#else 
...
#endif
```

**Comment by jm4R** [comment]
I guess we can. Longer code, but support C++11 here:
https://github.com/jm4R/fast_double_parser/commit/6f0fc7e5e6765654bae56a15abad4e0b286a239c

**Comment by lemire** [comment]
@jm4R Looks excellent to me. Can you issue a PR?

**Comment by jm4R** [comment]
I just did. I understand that documentation and tests remain on your side? ;)

**Comment by lemire** [comment]
@jm4R Yes. It is solid code unlikely to break stuff.
