### ISSUE TITLE
Attempt at creating a fast float parser

### ISSUE THREAD

**Issue by Eichenherz** [lemire/fast_double_parser#22]
Hello mr. Daniel Lemire and hello people interested in float parsing !
This is my shot at making a fast float parser: https://gist.github.com/Eichenherz/657b1d794325310f8eafa5af6375f673
Feel free to use is, dismantle it and/or improve it. 
If you spot issues and suggestions please do tell. 
NOTE: it's a "fixed format and accuracy attempt", cut to fit basically

**Comment by lemire** [comment]
Thanks for the link.

**Comment by Eichenherz** [comment]
Sure. Hope it will prove fruitful
