### ISSUE TITLE
question which build meant in Usage (benchmarks) ?

### ISSUE THREAD

**Issue by KhVictor777** [lemire/fast_double_parser#27]
In "usage" I see cd build - which build should I understand here?

https://github.com/lemire/fast_double_parser/blob/master/README.md#usage-benchmarks

**Comment by lemire** [comment]
This is only for benchmarks, there is no build needed for this library.

Assuming you want to build the benchmarks, are you familiar with cmake?

**Comment by KhVictor777** [comment]
No, I'm not. I'm not familiar with the cmake. I would like to build the benchmarks to see the results on my computer.

**Comment by lemire** [comment]
I flushed out the instructions but that won't help you much if you are not familiar with CMake in general.

```
git clone https://github.com/lemire/fast_double_parser.git
cd fast_double_parser
mkdir build
cd build
cmake ..
cmake --build . --config Release  
ctest .
./benchmark
```

I refer you to [CMake tutorials found on the Internet](https://cmake.org/cmake/help/latest/guide/tutorial/index.html). Documenting CMake usage in general is outside the scope of this project. Our usage of CMake is quite standard.

**Comment by KhVictor777** [comment]
Thanks Daniel! I followed your instructions and build went flawless
[victor@victora build]$./benchmark
parsing random integers in the range [0,1)


=== trial 1 ===
fast_double_parser  482.23 MB/s
fast_inplace_double_parser  428.54 MB/s
strtod         43.66 MB/s
abslfromch     89.33 MB/s
absl           94.31 MB/s
double-conv    103.61 MB/s


=== trial 2 ===
fast_double_parser  491.59 MB/s
fast_inplace_double_parser  404.09 MB/s
strtod         39.20 MB/s
abslfromch     77.80 MB/s
absl           84.15 MB/s
double-conv    96.89 MB/s


You can also provide a filename: it should contain one string per line corresponding to a number
[victor@victora build]$ ./benchmark ../benchmarks/data/canada.txt
read 111126 lines 


=== trial 1 ===
fast_double_parser  471.11 MB/s
fast_inplace_double_parser  454.76 MB/s
strtod         63.51 MB/s
abslfromch     182.90 MB/s
absl           157.16 MB/s
double-conv    91.54 MB/s


=== trial 2 ===
fast_double_parser  456.72 MB/s
fast_inplace_double_parser  429.08 MB/s
strtod         60.08 MB/s
abslfromch     188.47 MB/s
absl           179.72 MB/s
double-conv    88.97 MB/s


[victor@victora build]$ lscpu | grep Model
Model:                           30
Model name:                      Intel(R) Core(TM) i7 CPU       Q 720  @ 1.60GHz

**Comment by lemire** [comment]
Happy to hear that. Glad I was able to help.
