### ISSUE TITLE
Question: Does this project support/plans to locale-independent parsing?

### ISSUE THREAD

**Issue by AlbertoEAF** [lemire/fast_double_parser#29]
Hello,

Does this project provide support for locale-independent parsing?

strtod and std::stod which uses it depend on the C locale which I cannot modify in my program, but I want to ignore it and parse everything as if I was in the default "C" locale where the decimal separator is a dot and there is no special formatting.

As your project says it uses the standard libraries as a fallback I assume the answer is no?

Thank you

**Comment by lemire** [comment]
It parses strings according to RFC 7159. So, yes, it is locale-independent.

**Comment by lemire** [comment]
Closing since we don't even support locale dependencies.

**Comment by AlbertoEAF** [comment]
Thank you lemire ;)
