### ISSUE TITLE
parse_number_inplace_base fails for "-0" and "0"

### ISSUE THREAD

**Issue by furaga31** [lemire/fast_double_parser#32]
I have found that parse_number_inplace_base fails returns false for inputs of "-0" or "0".  It is pretty clear the cause is at line 1244:

```C++
    uint64_t i;      // an unsigned int avoids signed overflows (which are bad)
    if (*p == '0') { // 0 cannot be followed by an integer
        ++p;
        if (p == pe)
            return false;
        if (is_integer(*p)) {
            return false;
        }
        i = 0;
    }
    else {
```

It is checking for a '0' just after the code that looks for a '-'.  If it finds the zero, it increments the pointer and checks to see if it is at the end pointer.  If so, it just gives up.  This rules out the function working for the case of a zero without a decimal separator or exponent.

To get this working, I had to change the action after `if (p == pe)` to assign a 0.0 (or -0.0 if '-' was found) to *outDouble and return true.  I presume there is likely a better fix than this, but it works in my limited use case.

It looks like a similar issue was already fixed in the null-terminated string version.  There is an issue13() function in there that tests this case, but not on the inplace version.

**Comment by lemire** [comment]
I removed this "inplace" code.  It was improperly tested.


If you need this functionality, I will consider re-inclusion but only if the code has been carefully tested first.

Thanks for the report.
