### ISSUE TITLE
Benchmarks don't build

### ISSUE THREAD

**Issue by pitrou** [lemire/fast_double_parser#35]
On git master, I get this error when trying to run the benchmarks:
```
../benchmarks/benchmark.cpp: In function ‘double findmax_fast_inplace_double_parser(const std::vector<std::__cxx11::basic_string<char> >&)’:
../benchmarks/benchmark.cpp:41:41: error: ‘parse_number_inplace’ is not a member of ‘fast_double_parser’
   41 |         bool isok = fast_double_parser::parse_number_inplace(st.c_str(), st.c_str() + st.size(), &x);
      |                                         ^~~~~~~~~~~~~~~~~~~~
../benchmarks/benchmark.cpp: In function ‘void validate(const std::vector<std::__cxx11::basic_string<char> >&)’:
../benchmarks/benchmark.cpp:196:32: error: ‘parse_number_inplace’ is not a member of ‘fast_double_parser’
  196 |     isok = fast_double_parser::parse_number_inplace(st.c_str(), st.c_str()+st.size(), &x);
      |                                ^~~~~~~~~~~~~~~~~~~~
```

It seems sufficient to disable the "inplace" benchmarks (referring to a disappeared API?).

For the record, I get these numbers here (on a AMD Zen 2 CPU). Impressive.
```
$ ./benchmark ../benchmarks/data/canada.txt 
read 111126 lines 

=== trial 1 ===
fast_double_parser  1088.59 MB/s
strtod         173.18 MB/s
abslfromch     463.80 MB/s
absl           430.99 MB/s
double-conv    239.51 MB/s


=== trial 2 ===
fast_double_parser  1099.00 MB/s
strtod         176.60 MB/s
abslfromch     466.92 MB/s
absl           434.37 MB/s
double-conv    244.34 MB/s
```

**Comment by lemire** [comment]
Thanks for your report.

I removed a contributed function parse_number_inplace that was not properly tested. I will update the repo right away.

**Comment by pitrou** [comment]
(also, for the record, I am going to try integrating this library in Apache Arrow, since it could speed up CSV conversion quite significantly :-))

**Comment by lemire** [comment]
@pitrou This could be of interest to you then...

https://github.com/microsoft/LightGBM/pull/3405

Make sure to ping me if you get anywhere, so I can add a reference and credit you.

**Comment by pitrou** [comment]
Thanks for the pointer. I plan to avoid locale issues by falling back to double-conversion rather than `strtod` in the corner cases.

**Comment by lemire** [comment]
@pitrou That works. 

I am hoping to keep fast_double_parser light so a fallback to the system is probably fine.

In simdjson, we use 
https://github.com/simdjson/simdjson/blob/master/src/from_chars.cpp



Note that in the near future, I will release a complete from_chars implementation (complete as far as floats are concerned) that has the same speed as fast_double_parser, but without strtod_l, and with a different API.
