### ISSUE TITLE
parse_number() does not take nor return string length

### ISSUE THREAD

**Issue by pitrou** [lemire/fast_double_parser#37]
`parse_number` seems to assume it will never access memory out of bounds while iterating over user input (which is ok if the input string is null-terminated, but it need not be).

It also doesn't return the number of consumed bytes, so the caller doesn't know whether there were trailing non-numeric data in the input.

I can put up a PR if you think this would be an acceptable API change.

**Comment by pitrou** [comment]
A possible API is this:
```c++
static constexpr size_t kInvalidInput = 0;

size_t parse_number(const char *p, size_t length, double *outDouble);
```

**Comment by lemire** [comment]
@pitrou If you want a C++ approach, you might prefer:

https://github.com/lemire/fast_float

It probably does everything you want.

> seems to assume it will never access memory out of bounds while iterating over user input (which is ok if the input string is null-terminated, but it need not be).

It works like the standard function `strtod`. 

I am going to close this. If `fast_float` does not work for you, please do not hesitate to open a new issue, either here or at  https://github.com/lemire/fast_float

**Comment by pitrou** [comment]
`fast_float` would probably work, except that it claims to require C++17. We are only C++11-compatible (because of various platforms we need to support). Which C++17 features does `fast_float` require exactly?

**Comment by lemire** [comment]
It does not require C++17. Let me check that to make sure it is not misleading.

It is "C++17 -like" in that it uses an API that is "like C++17".

**Comment by lemire** [comment]
@pitrou  You are right that it is misleading. But no, C++17 is not required.

Let me fix that.

**Comment by wojdyr** [comment]
I came with a similar question half a year later. I see in the fast_float README:

> the library itself only requires C++11

but later on in the Requirements section:

> Thus we expect C++17 support. Though it might be reasonable to want C++17 features as part of old compilers, support old systems is not an objective of this library.

Just to make sure: C++17 support is expected, but not yet required to use the library?

In any case, thanks for writing this library, it's a great help.

**Comment by lemire** [comment]
@wojdyr The issue you are raising here is with https://github.com/lemire/fast_double_parser/ which has no such requirement.

Regarding the requirements section of fast_float, I have removed this section from the README as it was unnecessarily confusing. We do require C++11 but nothing more.
