### ISSUE TITLE
"1.0e10", it should return a 64-bit floating-point value equal to 10.

### ISSUE THREAD

**Issue by Kri-Ol** [lemire/fast_double_parser#4]
No, it shouldn't

**Comment by astrelsky** [comment]
> No, it shouldn't

1×10 = 10.

**Comment by astrelsky** [comment]
> No, it shouldn't

Should be 1×10^10. I had to look twice as well.

**Comment by lemire** [comment]
Thank you for pointing out the mistake. I appreciate it.

**Comment by astrelsky** [comment]
> Thank you for pointing out the mistake. I appreciate it.

@lemire 1.0e10 is 10,000,000,000

**Comment by lemire** [comment]
Yes. Of course.

**Comment by astrelsky** [comment]
> Yes. Of course.

Was just making sure as I saw the readme was changed to say it should return 100.

**Comment by lemire** [comment]
@astrelsky Because I thought it said 1.0e1. :-)

**Comment by lemire** [comment]
This is an example where one screws up on the easiest part of an explanation because one assumes it requires no thought.
