### ISSUE TITLE
A note about copyrights and license in the header file?

### ISSUE THREAD

**Issue by wojdyr** [lemire/fast_double_parser#53]
Would you mind adding license info to the header file?

I dropped the header into my project, but I feel bad not including any author/license info. I guess I should also drop one of the license files, but then I'd need to create a new directory for these two files, to make it clear that the license is for this one header.

Most of the single-header libraries have license at the beginning or at the end of the file (vast majority at the beginning, stb libraries have license at the end - like [here][1]).

[1]:  https://github.com/nothings/stb/blob/master/stb_sprintf.h#L1839

**Comment by lemire** [comment]
I do not like to push licensing information in the code, as I feel that it adds noisy boilerplate. This being said, if you send a pull request with licensing information, I will take it.



I should note that if you want to support our work, the best way to do so is to acknowledge fast_double_parser in your documentation.

**Comment by wojdyr** [comment]
That's fine, it's not necessary for me. I'll of course acknowledge using the library in documentation.
