### ISSUE TITLE
abseil-cpp graphcycles.cc error: 'numeric_limits'

### ISSUE THREAD

**Issue by Victorlab1** [lemire/fast_double_parser#55]
failed the compile today the latest

fast_double_parser/benchmarks/dependencies/abseil-cpp/absl/synchronization/internal/graphcycles.cc:454:26: error: 'numeric_limits' is not a member of 'std'
  454 |   if (x->version == std::numeric_limits<uint32_t>::max()) {

gcc (GCC) 11.1.0

#include <limits> solves it. Master of abseil-cpp has it

would not happen to Mac compiler according to https://stackoverflow.com/questions/4798936/numeric-limits-was-not-declared-in-this-scope-no-matching-function-for-call-t

**Comment by lemire** [comment]
Thanks for the report. The file `graphcycles.cc` is not part of the `fast_double_parser` but rather part of `abseil-cpp` and we use a recent release of `abseil-cpp` (March 2020).

A pull request would be welcome, but I do not plan to investigate this issue further.
