### ISSUE TITLE
Fails parsing "-.2839084827"

### ISSUE THREAD

**Issue by ghorwin** [lemire/fast_double_parser#57]
Passing the string "-.2839084827" results in parse error.

**Comment by lemire** [comment]
This library enforces RFC 7159 (JSON standard) which forbids this float.
<img width="395" alt="Screen Shot 2021-08-20 at 2 17 26 PM" src="https://user-images.githubusercontent.com/391987/130276650-f06f92ab-c9ef-4799-86ee-0e27a44be5c2.png">

If you are not interested in  RFC 7159, then please try https://github.com/fastfloat/fast_float

**Comment by ghorwin** [comment]
Ok, understood. However, the patch to make it work is really small... how about a "NON_STRIC_RFC7159" ifdef and the following code:

```c++
really_inline bool parse_number_base(const char *p, double *outDouble) {
	const char *pinit = p;
	bool found_minus = (*p == '-');
	bool negative = false;
	if (found_minus) {
		++p;
		negative = true;
#ifdef  NON_STRIC_RFC7159
		if (!is_one_of<DecSeparators...>(*p) && !is_integer(*p)) { // a negative sign must be followed by an integer or a decimal separator
#else //  NON_STRIC_RFC7159
		if (!is_integer(*p)) { // a negative sign must be followed by an integer
#endif
			return false;
		}
	}
	const char *const start_digits = p;

	uint64_t i;      // an unsigned int avoids signed overflows (which are bad)
#ifdef  NON_STRIC_RFC7159
	if (is_one_of<DecSeparators...>(*p)) { // number starts with a decimal separator?
		i = 0;
	}
	else 
#endif
	if (*p == '0') { // 0 cannot be followed by an integer
...

```

**Comment by lemire** [comment]
Can you explain why you want to use fast_double_parser for the C locale (given that it is specifically not designed for the C locale) when there is another, arguably better, library https://github.com/fastfloat/fast_float which supports the full C locale?

I am genuinely curious. It seems to me that the functionality you desire is already available in fast_float.

**Comment by ghorwin** [comment]
Sorry, didn't know fast_float and have used only FastDoubleParser so far... will switch now to the other lib. Thanks for pointing this out.
