### ISSUE TITLE
can you provide a variant for wstring?

### ISSUE THREAD

**Issue by dangdkhanh** [lemire/fast_double_parser#58]

**Comment by dangdkhanh** [comment]
I'm not sure it works after changing to wchar_t

**Comment by lemire** [comment]
We only support UTF-8/ASCII.

It is entirely possible to support other character encodings: pull requests invited.

**Comment by dangdkhanh** [comment]
Thanks you. exactly what i needed!!

**Comment by lemire** [comment]
We shall wait for you pull request.

**Comment by lemire** [comment]
I am closing this. The reporter should provide a pull request in the future.
