### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by jmbnyc** [lemire/fast_double_parser#59]
Not sure if you aware of this but I hit compiler error when attempting to git clone and then run benchmarks. I'm posting here in case you are not aware and I have made not attempt (as of yet) to debug/fix.

gcc version 11.2.0 (Ubuntu 11.2.0-7ubuntu2) 

Scanning dependencies of target absl_graphcycles_internal
[ 50%] Building CXX object benchmarks/dependencies/abseil-cpp/absl/synchronization/CMakeFiles/absl_graphcycles_internal.dir/internal/graphcycles.cc.o
/home/jmb/ldev/fast_double_parser/benchmarks/dependencies/abseil-cpp/absl/synchronization/internal/graphcycles.cc: In member function ‘void absl::synchronization_internal::GraphCycles::RemoveNode(void*)’:
/home/jmb/ldev/fast_double_parser/benchmarks/dependencies/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:26: error: ‘numeric_limits’ is not a member of ‘std’
  451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                          ^~~~~~~~~~~~~~
/home/jmb/ldev/fast_double_parser/benchmarks/dependencies/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:49: error: expected primary-expression before ‘>’ token
  451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                                                 ^
/home/jmb/ldev/fast_double_parser/benchmarks/dependencies/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:52: error: ‘::max’ has not been declared; did you mean ‘std::max’?
  451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                                                    ^~~
      |                                                    std::max
In file included from /usr/include/c++/11/algorithm:62,
                 from /home/jmb/ldev/fast_double_parser/benchmarks/dependencies/abseil-cpp/absl/synchronization/internal/graphcycles.cc:38:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
gmake[2]: *** [benchmarks/dependencies/abseil-cpp/absl/synchronization/CMakeFiles/absl_graphcycles_internal.dir/build.make:82: benchmarks/dependencies/abseil-cpp/absl/synchronization/CMakeFiles/absl_graphcycles_internal.dir/internal/graphcycles.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2430: benchmarks/dependencies/abseil-cpp/absl/synchronization/CMakeFiles/absl_graphcycles_internal.dir/all] Error 2
gmake: *** [Makefile:160: all] Error 2

**Comment by lemire** [comment]
You are having trouble with compiling a separate library, abseil. It is not our code. 

It might be possible to fix your issue by upgrading the abseil dependency. Please try to do so.

**Comment by lemire** [comment]
Go to abseil-cpp and do a pull.

**Comment by lemire** [comment]
If it solves your issue, please consider doing a pull request.

**Comment by jmbnyc** [comment]
Daniel,
Yes, I was aware that the compilation issue was with abseil - I was trying to run the benchmark so I was just trying to inform you that the abseil dependency for the benchmark fails to compile. I thought it did a fresh pull during the dependency build process but perhaps I was just not paying close attention. I can certainly give that a try.

**Comment by lemire** [comment]
Your issue is with the abseil (Google) library. It seems likely that you have a recent compiler that exposes some issue with the abseil version we are using. The solution is almost surely to update abseil. Can you confirm that you did the following while in the submodule...

```
git pull origin versionyourwant
```

If it fixes your problem, you just come back and do a pull request here.

**Comment by lemire** [comment]
I am closing this. The reporter has an issue with `abseil` (an external dependency only used with, optionally, running the benchmarks), not with `[fast_double_parser](https://github.com/lemire/fast_double_parser)`. The benchmarks are not compiled by default.

If folks have concerns, they should issue pull requests.
