### ISSUE TITLE
Release plans

### ISSUE THREAD

**Issue by gerion0** [lemire/fast_double_parser#78]
What are your release plans? What do you think of a new release in the next time? Since the last release a lot has changed. Especially the CMakeLists.txt contains install targets now, so the package can be installed in the system.

I currently try [to package Organicmaps for Gentoo](https://github.com/gentoo/guru/pull/185) that uses fast_double_parser (optionally as external library) and would like to package a release rather the git version.

**Comment by lemire** [comment]
Released https://github.com/lemire/fast_double_parser/releases/tag/v0.8.0

**Comment by gerion0** [comment]
Nice, thank you!
