### ISSUE TITLE
Include tests with updated Gay code

### ISSUE THREAD

**Issue by lemire** [lemire/fast_double_parser#8]
David Gay’s dtoa.c has updated (2016) with 96-bits big float, which speed up his earlier version,  see CHANGES dated 20160429,
http://www.netlib.org/fp/

It is possible that strtod has evolved too!

**Comment by lemire** [comment]
Ping @michaeleisel

**Comment by michaeleisel** [comment]
Makes sense. Is this just an FYI or can I help in some way?

**Comment by lemire** [comment]
This is dtoa so not directly relevant but it might be important to test the latest strtod from Gay’s.

**Comment by lemire** [comment]
We need to find the best version of strtod... and it may not be in the standard libraries.

**Comment by lemire** [comment]
The following project includes such tests:
https://github.com/lemire/simple_fastfloat_benchmark

It is with a new library, but the speeds should be similar.

Closing.
